services:
  admin:
    build: .
    image: yeoboya-lunch-admin:latest
    container_name: admin_container
    restart: unless-stopped
    networks:
      - yeoboya_lunch_network
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    ports:
      - "3001:3001"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
#      interval: 10s
#      retries: 5
#      timeout: 5s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512MB"

networks:
  yeoboya_lunch_network:
    name: yeoboya_lunch_network
    external: true

volumes:
  mysql_data:
    name: yeoboya_lunch_mysql_data
  redis_data:
    name: yeoboya_lunch_redis_data
